-- =========================================================================
-- Supabase SQL Schema for Minimal Personal Finance & Portfolio Dashboard
-- Multi-User Isolation Edition (ระบบแยกข้อมูลผู้ใช้งาน)
-- Run this in Supabase -> SQL Editor -> New Query -> Run
-- =========================================================================

-- 0. Users table (Authentication & Profile)
CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ DEFAULT NOW()
);

-- 1. Assets table (Investment Portfolio & Fixed Assets per user)
CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    current_value NUMERIC NOT NULL DEFAULT 0,
    cost_basis NUMERIC NOT NULL DEFAULT 0,
    target_allocation NUMERIC NOT NULL DEFAULT 0,
    monthly_dca NUMERIC NOT NULL DEFAULT 0,
    expected_roi NUMERIC NOT NULL DEFAULT 6.0,
    platform_or_broker TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    asset_type TEXT NOT NULL DEFAULT 'investment',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Liabilities table (Debts / Loans per user)
CREATE TABLE IF NOT EXISTS liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    total_balance NUMERIC NOT NULL DEFAULT 0,
    monthly_payment NUMERIC NOT NULL DEFAULT 0,
    interest_rate NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Monthly Financial Profile (Active Estimate per user)
CREATE TABLE IF NOT EXISTS monthly_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    salary NUMERIC NOT NULL DEFAULT 50000,
    bonus_or_other_income NUMERIC NOT NULL DEFAULT 0,
    passive_income NUMERIC NOT NULL DEFAULT 0,
    fixed_expenses NUMERIC NOT NULL DEFAULT 15000,
    variable_expense_estimate NUMERIC NOT NULL DEFAULT 15000,
    emergency_fund_target_months INTEGER NOT NULL DEFAULT 6,
    fire_target_monthly_spend NUMERIC NOT NULL DEFAULT 35000,
    fire_expected_return NUMERIC NOT NULL DEFAULT 7.0,
    fire_inflation_rate NUMERIC NOT NULL DEFAULT 2.5,
    fire_birth_year INTEGER NOT NULL DEFAULT 1996,
    fire_current_age INTEGER NOT NULL DEFAULT 30,
    fire_target_age INTEGER NOT NULL DEFAULT 50,
    fire_monthly_dca NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Itemized Income Items per user
CREATE TABLE IF NOT EXISTS income_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    income_type TEXT NOT NULL DEFAULT 'ประจำ (Active / Fixed)',
    estimated_amount NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Itemized Expense Items per user
CREATE TABLE IF NOT EXISTS expense_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    expense_type TEXT NOT NULL DEFAULT 'คงที่ (Fixed)',
    estimated_amount NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Custom Categories per user
CREATE TABLE IF NOT EXISTS custom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    cat_type TEXT NOT NULL,
    name TEXT NOT NULL
);

-- 7. Monthly Snapshots (Historic tracking per user)
CREATE TABLE IF NOT EXISTS monthly_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    snapshot_month TEXT NOT NULL,
    income NUMERIC NOT NULL DEFAULT 0,
    expenses NUMERIC NOT NULL DEFAULT 0,
    savings_invested NUMERIC NOT NULL DEFAULT 0,
    total_assets NUMERIC NOT NULL DEFAULT 0,
    total_debts NUMERIC NOT NULL DEFAULT 0,
    net_worth NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Future Cash Flows & Insurance Annuity per user
CREATE TABLE IF NOT EXISTS future_cashflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    flow_type TEXT NOT NULL DEFAULT 'เงินก้อนครั้งเดียว (Lump Sum)',
    amount NUMERIC NOT NULL DEFAULT 0,
    start_age INTEGER NOT NULL DEFAULT 60,
    end_age INTEGER NOT NULL DEFAULT 60,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- MIGRATION SCRIPT FOR EXISTING DATABASES:
-- If you already have existing tables, run the following block to add user_id:
-- =========================================================================
ALTER TABLE assets ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE liabilities ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE monthly_profile ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE income_items ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE expense_items ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE custom_categories ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE monthly_snapshots ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE future_cashflows ADD COLUMN IF NOT EXISTS user_id BIGINT;

-- Enable Row Level Security (RLS) & Anon Access Policies
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE future_cashflows ENABLE ROW LEVEL SECURITY;

-- Allow anon policies for REST API operations (Safe Idempotent Re-runs)
DROP POLICY IF EXISTS "Allow anon all on app_users" ON app_users;
CREATE POLICY "Allow anon all on app_users" ON app_users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on assets" ON assets;
CREATE POLICY "Allow anon all on assets" ON assets FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on liabilities" ON liabilities;
CREATE POLICY "Allow anon all on liabilities" ON liabilities FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on monthly_profile" ON monthly_profile;
CREATE POLICY "Allow anon all on monthly_profile" ON monthly_profile FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on income_items" ON income_items;
CREATE POLICY "Allow anon all on income_items" ON income_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on expense_items" ON expense_items;
CREATE POLICY "Allow anon all on expense_items" ON expense_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on custom_categories" ON custom_categories;
CREATE POLICY "Allow anon all on custom_categories" ON custom_categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on monthly_snapshots" ON monthly_snapshots;
CREATE POLICY "Allow anon all on monthly_snapshots" ON monthly_snapshots FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on future_cashflows" ON future_cashflows;
CREATE POLICY "Allow anon all on future_cashflows" ON future_cashflows FOR ALL USING (true) WITH CHECK (true);


