-- =========================================================================
-- Supabase SQL Schema for Minimal Personal Finance & Portfolio Dashboard
-- Run this in Supabase -> SQL Editor -> New Query -> Run
-- =========================================================================

-- 1. Assets table (Investment Portfolio & Fixed Assets)
CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    current_value NUMERIC NOT NULL DEFAULT 0,
    cost_basis NUMERIC NOT NULL DEFAULT 0,
    target_allocation NUMERIC NOT NULL DEFAULT 0,
    monthly_dca NUMERIC NOT NULL DEFAULT 0,
    expected_roi NUMERIC NOT NULL DEFAULT 6.0,
    platform_or_broker TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    asset_type TEXT NOT NULL DEFAULT 'investment',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Liabilities table (Debts / Loans)
CREATE TABLE IF NOT EXISTS liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    total_balance NUMERIC NOT NULL DEFAULT 0,
    monthly_payment NUMERIC NOT NULL DEFAULT 0,
    interest_rate NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Monthly Financial Profile (Active Estimate)
CREATE TABLE IF NOT EXISTS monthly_profile (
    id BIGINT PRIMARY KEY DEFAULT 1,
    salary NUMERIC NOT NULL DEFAULT 50000,
    bonus_or_other_income NUMERIC NOT NULL DEFAULT 0,
    passive_income NUMERIC NOT NULL DEFAULT 0,
    fixed_expenses NUMERIC NOT NULL DEFAULT 15000,
    variable_expense_estimate NUMERIC NOT NULL DEFAULT 15000,
    emergency_fund_target_months INTEGER NOT NULL DEFAULT 6,
    fire_target_monthly_spend NUMERIC NOT NULL DEFAULT 35000,
    fire_expected_return NUMERIC NOT NULL DEFAULT 7.0,
    fire_inflation_rate NUMERIC NOT NULL DEFAULT 2.5,
    fire_current_age INTEGER NOT NULL DEFAULT 30,
    fire_target_age INTEGER NOT NULL DEFAULT 50,
    fire_monthly_dca NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert initial default monthly profile
INSERT INTO monthly_profile (id, salary, bonus_or_other_income, passive_income, fixed_expenses, variable_expense_estimate, emergency_fund_target_months, fire_target_monthly_spend, fire_expected_return, fire_inflation_rate, fire_current_age, fire_target_age, fire_monthly_dca)
VALUES (1, 65000, 5000, 2000, 18000, 16000, 6, 35000, 7.0, 2.5, 30, 50, 0)
ON CONFLICT (id) DO NOTHING;

-- 4. Itemized Income Items
CREATE TABLE IF NOT EXISTS income_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    income_type TEXT NOT NULL DEFAULT 'ประจำ (Active / Fixed)',
    estimated_amount NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Itemized Expense Items
CREATE TABLE IF NOT EXISTS expense_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    expense_type TEXT NOT NULL DEFAULT 'คงที่ (Fixed)',
    estimated_amount NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Custom Categories
CREATE TABLE IF NOT EXISTS custom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_type TEXT NOT NULL,
    name TEXT NOT NULL,
    UNIQUE(cat_type, name)
);

-- 7. Monthly Snapshots (Historic tracking)
CREATE TABLE IF NOT EXISTS monthly_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_month TEXT UNIQUE NOT NULL,
    income NUMERIC NOT NULL DEFAULT 0,
    expenses NUMERIC NOT NULL DEFAULT 0,
    savings_invested NUMERIC NOT NULL DEFAULT 0,
    total_assets NUMERIC NOT NULL DEFAULT 0,
    total_debts NUMERIC NOT NULL DEFAULT 0,
    net_worth NUMERIC NOT NULL DEFAULT 0,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) or Allow Public Access (For personal app)
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE income_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_snapshots ENABLE ROW LEVEL SECURITY;

-- Create Open Policies for Anon key (Personal Dashboard)
CREATE POLICY "Allow anon read all on assets" ON assets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read all on liabilities" ON liabilities FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read all on monthly_profile" ON monthly_profile FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read all on income_items" ON income_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read all on expense_items" ON expense_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read all on custom_categories" ON custom_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read all on monthly_snapshots" ON monthly_snapshots FOR ALL USING (true) WITH CHECK (true);
